#!/bin/bash
# tools/detector_fp_tracker.sh — Stream-B substrate cron proof for skills/session-architecture v1.0.0.
#
# Samples each tools/test_*.sh detector for FP indication (exit code, output
# size, presence of red/yellow markers) and writes a dashboard.
#
# This v0.1 implementation does NOT itself ground-truth claims; it provides
# the surveillance surface that next-session reviewers can read to decide
# which detectors deserve upgrade or retirement.
#
# Output: pages/dashboards/detector-fp-rates.md (one row per detector).
# History: ~/nous-agaas/state/detector-fp-history.jsonl (append-only sample log)
# Manual overrides: pages/dashboards/detector-fp-overrides.json
#
# Schedule: hourly via launchd. Pure shell, no LLM, no Opus burn.
# Bash 3.2 compatible (no associative arrays).

set -u
VAULT="/Users/madia/Documents/Projects/Nous AGaaS/Nous"
TOOLS="$VAULT/tools"
OUT="$VAULT/pages/dashboards/detector-fp-rates.md"
OVERRIDES="$VAULT/pages/dashboards/detector-fp-overrides.json"
HISTORY="$HOME/nous-agaas/state/detector-fp-history.jsonl"
mkdir -p "$(dirname "$HISTORY")"
mkdir -p "$(dirname "$OUT")"

NOW=$(date +%Y-%m-%dT%H:%M:%S%z | sed -E 's/([0-9]{2})([0-9]{2})$/\1:\2/')
TODAY=$(date +%Y-%m-%d)

# Discover detectors (tools/test_*.sh, exclude *_self.sh meta-tests).
DETECTORS=$(ls -1 "$TOOLS"/test_*.sh 2>/dev/null | grep -v _self.sh | sort)
DETECTOR_COUNT=$(echo "$DETECTORS" | grep -c .)

# Run each detector with a 10s timeout, capture exit code + truncated output.
# Build the per-detector row data into a tab-separated temp file.
ROWS=$(mktemp -t detector_fp_tracker.XXXXXX)
trap 'rm -f "$ROWS"' EXIT

while IFS= read -r det; do
  [ -z "$det" ] && continue
  name=$(basename "$det" .sh)
  # </dev/null prevents inner detectors from consuming the outer here-string stdin,
  # which would silently break the loop after the first iteration that reads stdin.
  out=$(timeout 10 bash "$det" --quiet </dev/null 2>&1 || true)
  code=$?
  size=${#out}
  if echo "$out" | grep -q '🔴\|FAIL\|RED'; then red=1; else red=0; fi
  if echo "$out" | grep -q '🟡\|WARN\|YELLOW'; then yellow=1; else yellow=0; fi
  fp_manual="—"
  if [ -s "$OVERRIDES" ]; then
    fp_val=$(jq -r --arg n "$name" '.[$n] // empty' "$OVERRIDES" 2>/dev/null)
    [ -n "$fp_val" ] && fp_manual="$fp_val"
  fi
  # Append history sample.
  jq -nc \
    --arg ts "$NOW" --arg name "$name" --argjson code "$code" \
    --argjson size "$size" --argjson red "$red" --argjson yellow "$yellow" \
    '{ts:$ts, detector:$name, exit:$code, output_size:$size, red:$red, yellow:$yellow}' >> "$HISTORY"
  # Append dashboard row (TSV).
  printf "%s\t%s\t%s\t%s\t%s\t%s\n" "$name" "$code" "$red" "$yellow" "$size" "$fp_manual" >> "$ROWS"
done <<< "$DETECTORS"

HISTORY_TOTAL=$(wc -l < "$HISTORY" 2>/dev/null | tr -d ' ' || echo 0)
OVERRIDE_COUNT=0
[ -s "$OVERRIDES" ] && OVERRIDE_COUNT=$(jq 'keys | length' "$OVERRIDES" 2>/dev/null || echo 0)

# Render dashboard markdown.
{
  echo "---"
  echo "type: dashboard"
  echo "id: DASH-DETECTOR-FP-RATES"
  echo "title: \"Detector FP-rate tracker — $TODAY\""
  echo "date: $TODAY"
  echo "tags: [dashboard, detector-fp-rate, stream-b-cron, session-architecture]"
  echo "status: reviewed"
  echo "last_updated: $TODAY"
  echo "related:"
  echo "  - \"[[skills/session-architecture/SKILL]]\""
  echo "  - \"[[skills/audit/SKILL]]\""
  echo "  - \"[[skills/karpathy-loop/SKILL]]\""
  echo "---"
  echo
  echo "# Detector FP-rate tracker — $TODAY"
  echo
  echo "Generated by \`tools/detector_fp_tracker.sh\` (Stream-B cron, hourly). Last run: \`$NOW\`."
  echo
  echo "## Summary"
  echo
  echo "- Detectors discovered: $DETECTOR_COUNT"
  echo "- History samples: $HISTORY_TOTAL total"
  echo "- Manual FP overrides: $OVERRIDE_COUNT"
  echo
  echo "## Per-detector this run"
  echo
  echo "| Detector | Exit | 🔴 | 🟡 | Output bytes | Manual FP rate |"
  echo "|---|---|---|---|---|---|"
  while IFS=$'\t' read -r name code red yellow size fp; do
    [ -z "$name" ] && continue
    red_glyph=$([ "$red" = "1" ] && echo "🔴" || echo "·")
    yellow_glyph=$([ "$yellow" = "1" ] && echo "🟡" || echo "·")
    echo "| \`$name\` | $code | $red_glyph | $yellow_glyph | $size | $fp |"
  done < "$ROWS"
  echo
  echo "## How to use"
  echo
  echo "- A detector with **high exit-1 rate AND no real bugs being caught** is a FP-rate candidate. Annotate via \`pages/dashboards/detector-fp-overrides.json\` with \`{\"detector_name\": 0.85}\` (manual FP rate)."
  echo "- Detectors with **manual FP rate > 0.70** queue for upgrade or retirement (per session-architecture AP-2 + audit AP-15 candidate)."
  echo "- Karpathy ground-truth: trust only detectors that pass a 90%+ true-positive bar."
  echo
  echo "## See also"
  echo
  echo "- [[skills/session-architecture/SKILL]] — Stream-B cron pattern"
  echo "- [[skills/audit/SKILL]] — detector ownership doctrine"
  echo "- [[skills/karpathy-loop/SKILL]] — ground-truth-over-recall"
  echo
  echo "## Timeline"
  echo
  echo "- **$TODAY** | s73-mac-44149: v0.1 first run. $DETECTOR_COUNT detectors discovered."
} > "$OUT"

echo "✅ detector_fp_tracker: $DETECTOR_COUNT detectors → $OUT"
