#!/bin/bash
# test_agent_autonomy.sh — mechanical enforcement of musk-algorithm AP-4
# (agent-autonomy loop: never stop for human factors; research + implement before escalation).
#
# Shipped session 68p 2026-04-23 after Madi corrected AP-4 violations 4 consecutive times
# in a single session. Each correction carried the same signal — deference-dressed-as-autonomy
# ("optional: X", "whenever ready", "still recommending", "your call", "need anything from me?",
# "if you want", "waiting for your ack", "suggested default") — phrases that LOOK autonomous
# but actually push a scope decision back to Madi. The billion-dollar-solopreneur pattern
# (Elon/Karpathy/Tan/Nate B. Jones) rejects this: decide first-principles yourself + execute +
# report facts, not options.
#
# What this detector scans:
#   1. HANDOFF-*.md files modified/added in the current diff (or in a given date range)
#   2. MEMORY.md top-block
#   3. git commit messages in the current commit range
#
# What it flags: any substantive decision line containing red-flag phrases listed below.
#
# Invoked by:
#   - Developer manual: bash tools/test_agent_autonomy.sh [FILE-GLOB-OR-PATH]...
#   - Pre-commit hook: scan staged HANDOFF/MEMORY
#   - Commit-msg hook: scan commit message via stdin
#   - Telegram send/factory outbound gates: scan outbound text via stdin
#
# Red-flag phrases (case-insensitive, word-boundary):
RED_FLAGS=(
  "optional:"
  "whenever ready"
  "whenever you"
  "your call"
  "your choice"
  "still recommending"
  "need anything from me"
  "anything from me\?"
  "if you want"
  "if you'd like"
  "waiting for your"
  "suggested default"
  "blocked on your"
  "blocked on madi"
  "need madi"
  "ask madi"
  "your decision"
  "awaiting your"
  "at your convenience"
  "let me know if"
  "let me know when"
  "green-light to"
  "green light to"
  "ready to execute"
  "ready to proceed"
  "should i"
  "should we"
  "shall i"
  "shall we"
  "which do you prefer"
  "which approach"
  "let me know which approach"
  "would you rather"
  "want me to .* or"
  "should i proceed"
  "should we proceed"
  "want me to proceed"
)
#
# HALL PASS phrases (if present near a red flag, mark the line as legitimate-escalation,
# not AP-4 violation):
HALL_PASS=(
  "physically-impossible-without-madi"
  "named-author-required"
  "3 cycles passed with no progress"
  "social-side-effect"
  "production-write-requires-ack"
)
#
# Bypass mechanism: none. This is a review-assist tool, not a commit gate (yet).
# Future: wire into pre-push hook as warning (not block).

set -u

self_test() {
  local self_abs
  self_abs="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
  local tmp
  tmp="$(mktemp -d)"
  trap 'rm -rf "${tmp:-}"' EXIT

  printf '%s\n' 'should I run the next validator or wait?' | "$self_abs" --stdin >"$tmp/red.out" 2>&1
  local red_exit=$?
  if [ "$red_exit" -ne 1 ]; then
    echo "FAIL self-test tactical red phrase: expected exit 1, got $red_exit"
    cat "$tmp/red.out"
    return 1
  fi

  printf '%s\n' 'Running the next validator now.' | "$self_abs" --stdin >"$tmp/green.out" 2>&1
  local green_exit=$?
  if [ "$green_exit" -ne 0 ]; then
    echo "FAIL self-test clean phrase: expected exit 0, got $green_exit"
    cat "$tmp/green.out"
    return 1
  fi

  echo "OK: agent-autonomy tactical phrase self-test passed"
}

if [ "${1:-}" = "--self-test" ]; then
  self_test
  exit $?
fi

# Build extended grep pattern
pattern=""
for p in "${RED_FLAGS[@]}"; do
  if [ -n "$pattern" ]; then pattern="${pattern}|${p}"; else pattern="$p"; fi
done

# Invocation modes:
#   (1) tools/test_agent_autonomy.sh                  → scan last 7 HANDOFFs + MEMORY (audit mode)
#   (2) tools/test_agent_autonomy.sh --staged         → scan git staged HANDOFF/MEMORY diffs only (pre-commit mode)
#   (3) tools/test_agent_autonomy.sh <file>...        → scan given files (commit-msg, explicit)
#   (4) echo "..." | tools/test_agent_autonomy.sh --stdin  → scan stdin content (tg_send pre-send, ad-hoc)
TARGETS=()
STDIN_MODE=0
STAGED_MODE=0

# SKIP merge commits (same rationale as test_skill_bump_requires_gbrain_timeline.sh —
# merge commit messages are auto-generated by git and propagate already-gated content).
if [ -f ".git/MERGE_MSG" ] && [ "${1:-}" != "--stdin" ]; then
  exit 0
fi

if [ "${1:-}" = "--stdin" ]; then
  STDIN_MODE=1
elif [ "${1:-}" = "--staged" ]; then
  STAGED_MODE=1
  # Only the STAGED portion of HANDOFF/MEMORY files → write to tmp files for scanning
  TMPDIR=$(mktemp -d)
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    case "$f" in
      pages/progress/HANDOFF-AUTO-*.md|pages/progress/claude-memory/MEMORY.md)
        tmpf="$TMPDIR/$(basename "$f")"
        git show ":$f" 2>/dev/null > "$tmpf" || continue
        TARGETS+=("$tmpf")
        ;;
    esac
  done < <(git diff --cached --name-only --diff-filter=AM 2>/dev/null || true)
elif [ -z "${1:-}" ]; then
  while IFS= read -r f; do
    TARGETS+=("$f")
  done < <(ls -t pages/progress/HANDOFF-AUTO-2026*.md 2>/dev/null | head -7 || true)
  TARGETS+=("pages/progress/claude-memory/MEMORY.md")
else
  TARGETS=("$@")
fi

VIOLATIONS=0
# STDIN mode: scan piped content as a single synthetic file
if [ "$STDIN_MODE" = "1" ]; then
  TMPF=$(mktemp)
  cat > "$TMPF"
  TARGETS=("$TMPF")
fi

# Empty-array guard (set -u + ${arr[@]} on bash <5 with empty array = unbound var)
if [ ${#TARGETS[@]} -eq 0 ]; then
  exit 0
fi

for f in "${TARGETS[@]}"; do
  [ -f "$f" ] || continue
  # Scan (case-insensitive) for red-flag phrases
  HITS=$(grep -niE "$pattern" "$f" 2>/dev/null || true)
  [ -z "$HITS" ] && continue

  # Filter out lines that contain HALL_PASS phrases (legitimate-escalation)
  FILTERED=""
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    PASS=0
    for hp in "${HALL_PASS[@]}"; do
      if echo "$line" | grep -qiE "$hp"; then PASS=1; break; fi
    done
    [ $PASS -eq 1 ] && continue
    FILTERED="${FILTERED}${line}"$'\n'
  done <<< "$HITS"

  [ -z "$FILTERED" ] && continue

  echo "⚠️  AP-4 VIOLATION SCAN: $f"
  echo "$FILTERED"
  echo ""
  V=$(echo "$FILTERED" | grep -c ':' || echo 0)
  VIOLATIONS=$((VIOLATIONS + V))
done

if [ $VIOLATIONS -gt 0 ]; then
  echo "============================================================" >&2
  echo "🔴 BLOCKED: $VIOLATIONS agent-autonomy (AP-4) violations" >&2
  echo "" >&2
  echo "Musk-algorithm AP-4: never stop for human factors." >&2
  echo "Karpathy/Tan/Nate B. Jones pattern: decide first-principles + execute + report." >&2
  echo "" >&2
  echo "For each red-flag line:" >&2
  echo "  (a) If the decision TRULY needs Madi input (cost-budget /" >&2
  echo "      social side-effect / named-author missing / 3-cycles-iterated)," >&2
  echo "      add a HALL-PASS phrase on or near the line:" >&2
  echo "          physically-impossible-without-madi" >&2
  echo "          named-author-required" >&2
  echo "          3 cycles passed with no progress" >&2
  echo "          social-side-effect" >&2
  echo "          production-write-requires-ack" >&2
  echo "  (b) Otherwise REMOVE the red-flag phrase and decide autonomously." >&2
  echo "" >&2
  echo "Bypass (operator risk, same as RULE ZERO):" >&2
  echo "  git commit --no-verify                (for git hooks)" >&2
  echo "  AUTONOMY_BYPASS=1 bash tools/tg_send.sh \"...\"  (for Telegram)" >&2
  echo "" >&2
  echo "Cross-ref: pages/skills/musk-algorithm/SKILL.md AP-4." >&2
  echo "============================================================" >&2
  exit 1  # HARD BLOCK
fi

exit 0
